name = "tetrashop-unified-system"
compatibility_date = "2024-01-01"
main = "unified-worker.js"

[vars]
SYSTEM_MODE = "production"
ENVIRONMENT = "unified"
VERSION = "1.0.0"

[env.production]
name = "tetrashop-unified-production"
