name = "tetrashop-optimized"
compatibility_date = "2024-10-23"
pages_build_output_dir = "./dist"

[env.production]
account_id = "YOUR_ACCOUNT_ID"
zone_id = "YOUR_ZONE_ID"

[vars]
APP_NAME = "تتراشاپ"
ROI_BASE = "341"
ROI_BONUS = "10"
APP_VERSION = "2.0.0"

[[routes]]
pattern = "tetrashop.ir/*"
custom_domain = true
